### ISSUE TITLE
Deployment Fails - VM Name already in use

### ISSUE THREAD

**Issue by adamswbrown** [krnese/AzureDeploy#15]
Deployment Fails with: 

New-AzureRmResourceGroupDeployment : 09:15:32 - Resource Microsoft.Resources/deployments 
'deployVMs' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment 
operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"DnsRecordInUse\",\r\n    
\"message\": \"DNS record workloadvm1.westeurope.cloudapp.azure.com is already used by another 
public IP.\",\r\n    \"details\": []\r\n  }\r\n}"
          },
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"DnsRecordInUse\",\r\n    
\"message\": \"DNS record workloadvm0.westeurope.cloudapp.azure.com is already used by another 
public IP.\",\r\n    \"details\": []\r\n  }\r\n}"
          },
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"DnsRecordInUse\",\r\n    
\"message\": \"DNS record workloadvm2.westeurope.cloudapp.azure.com is already used by another 
public IP.\",\r\n    \"details\": []\r\n  }\r\n}"
          },
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"DnsRecordInUse\",\r\n    
\"message\": \"DNS record workloadvm3.westeurope.cloudapp.azure.com is already used by another 
public IP.\",\r\n    \"details\": []\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}'
At line:18 char:1
+ New-AzureRmResourceGroupDeployment -Name myDemo `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.New 
   AzureResourceGroupDeploymentCmdlet
 
New-AzureRmResourceGroupDeployment : 09:15:33 - At least one resource deployment operation 
failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for 
usage details.
At line:18 char:1
+ New-AzureRmResourceGroupDeployment -Name myDemo `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.New 
   AzureResourceGroupDeploymentCmdlet

Is there a way to change the name of the VM's that are deployed?

**Comment by krnese** [comment]
You are free to assign any vm name you want, to the PowerShell example. The existing recipe is only an example :-)
