### ISSUE TITLE
AzureDeploy OMSDemo - Error creating DSC Config - The location property is required for this definition

### ISSUE THREAD

**Issue by marenskoetter** [krnese/AzureDeploy#16]
Error deploying  "AzureDeploy/OMS/MSOMS/OMSDemo/"
The DSC Configuration within Automation Account don't get created with following error.

new-AzureRmResourceGroupDeployment : 21:07:21 - Resource Microsoft.Automation/automationAccounts/Configurations
maDemoAutomationAccount/OMSASR' failed with message '{
 "error": {
   "code": "LocationRequired",
   "message": "The location property is required for this definition."
 }
'
n Zeile:1 Zeichen:1
 New-AzureRmResourceGroupDeployment -Name maDemo `
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
   + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

ew-AzureRmResourceGroupDeployment : 21:07:21 - Resource Microsoft.Automation/automationAccounts/Configurations
maDemoAutomationAccount/OMS' failed with message '{
 "error": {
   "code": "LocationRequired",
   "message": "The location property is required for this definition."
 }
'
n Zeile:1 Zeichen:1
 New-AzureRmResourceGroupDeployment -Name maDemo `
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
   + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

ew-AzureRmResourceGroupDeployment : 21:07:21 - Resource Microsoft.Automation/automationAccounts/Configurations
maDemoAutomationAccount/OMSSERVICE' failed with message '{
 "error": {
   "code": "LocationRequired",
   "message": "The location property is required for this definition."
 }
'
n Zeile:1 Zeichen:1
 New-AzureRmResourceGroupDeployment -Name maDemo `
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
   + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by krnese** [comment]
should be fixed now. Do you  mind giving it a try and let me know how it goes?

**Comment by jefutte** [comment]
I just tested and got the same error. I think you added it to the wrong file?
You changed: ARM\lab4\nestedTemplates\dscConfigs.json
Template is referencing: OMS\MSOMS\OMSDemo\nestedTemplates\dscConfigs.json

**Comment by krnese** [comment]
Thanks. I will do a clean-up shortly, and move this sample over to quickstart.
