### ISSUE TITLE
No HTTP resource was found rg create

### ISSUE THREAD

**Issue by cloudmelon** [krnese/AzureDeploy#21]
I think the api not ready that's why I have the following error 

"No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/f42b4319-067a-4548-a650-33a1553b3a42/resourcegroups/qstci-4952f590-f80b-da48-bf2d-af63a32294dc/providers/Microsoft.Resources/resourceGroups/azure-rg?api-version=2018-05-01'

![screen shot 2018-08-04 at 09 16 50](https://user-images.githubusercontent.com/4621560/43673681-4682b038-97c7-11e8-807b-4274602ac77e.png)

I noticed that 
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.1",

so I changed also the parametters as 1.0.0.1 version ( don't change schema ) 

Could you please check that ? thanks

**Comment by krnese** [comment]
To deploy subscription level resources, you must use "az deployment create" with AzureCLI currently.
We're in the process of updating PowerShell as well, which will be "New-AzureRmDeployment".
The new deployment API sit at the subscription level, hence targeting resource group for deploying this will fail.
