### ISSUE TITLE
Wrong api for deployment at subscription scope

### ISSUE THREAD

**Issue by peterschen** [krnese/AzureDeploy#25]
In /ARM/deployments/rgCreate.json the Microsoft.Resources/deployment references API version 2017-05-10. For deployments at subscription scope at least API version 2018-05-01 is required.

**Comment by sraddhananda** [comment]
Hi @peterschen , would you please check the below link.
https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/2017-05-10/deployments.
