### ISSUE TITLE
ASRautomation template: The scripts folder was deleted back on December 15th of 2016 and the template fails to run.

### ISSUE THREAD

**Issue by mylameaccount** [krnese/AzureDeploy#5]
Important files for the running of the script are missing and were deleted on December 15h. These need to be fixed for the asrautomation template to work.

https://github.com/krnese/AzureDeploy/tree/439c08dc5108166768108e50dc3f8a67c14c31ba/OMS/MSOMS/Solutions/asrautomation/scripts

**Comment by krnese** [comment]
We've pulled the samples since we introduced some changes to the backend for recovery plans, that caused the scripts to fail. We are about to release new versions shortly.
