### ISSUE TITLE
Deployment failure with existing resources....OMS (node) pricing tier

### ISSUE THREAD

**Issue by x0techdad** [krnese/AzureDeploy#6]
It failed with existing OMS WS, AA account, and Recovery Vault. The error referenced the WS and AA already being linked and the pricing plans not matching.....they do match. Forked the template and looking to see if there is a hard coded pricing plan.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"code\": \"Conflict\",\r\n \"message\": \"Automation account is linked to workspace, it's pricing plan must be same as workspace. SubscriptionId: aaasdfaserasvadfdsf AccountName: pres-use-automation WorkspaceId: /subscriptions/aaasdfaserasvadfdsf/resourcegroups/pres-use-oms-rg/providers/microsoft.operationalinsights/workspaces/pres-use-oms.\"\r\n}"}]}

**Comment by krnese** [comment]
Which template was this?

**Comment by thebitstreamer** [comment]
Same here for the Azure Storage Analytics Preview

**Comment by krnese** [comment]
Thanks - but please file it into our QuickStart repo
