### ISSUE TITLE
Deployment failed. Error states issues with pricing plan

### ISSUE THREAD

**Issue by BertWolters** [krnese/AzureDeploy#7]
/subscriptions/14aa6c84-a04a-4dcc-a284-25ee6c690b99/resourceGroups/rg-oms-workspace/providers/Microsoft.Resources/deployments/azureBackupAnalytics
StatusMessage{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"code\": \"Conflict\",\r\n  \"message\": \"Automation account is linked to workspace, it's pricing plan must be same as workspace. SubscriptionId: 14aa6c84-a04a-4dcc-a284-25ee6c690b99 AccountName: MSPG-Automation-OMS WorkspaceId: /subscriptions/14aa6c84-a04a-4dcc-a284-25ee6c690b99/resourcegroups/rg-oms-workspace/providers/microsoft.operationalinsights/workspaces/msplayground.\"\r\n}"

**Comment by krnese** [comment]
Thanks @BertWolters - but you need to use a dedicated automation account - that is not linked to a workspace for this solution.
